/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/clover.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Curve005: THREE.Mesh
    Curve005_1: THREE.Mesh
    Curve005_2: THREE.Mesh
  }
  materials: {
    ['3DPrint_Green_Leaf']: THREE.MeshStandardMaterial
    ['3DPrint_White_Frame']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/clover.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0.001]} rotation={[0, -0.076, 0]}>
        <mesh geometry={nodes.Curve005.geometry} material={materials['3DPrint_Green_Leaf']} />
        <mesh geometry={nodes.Curve005_1.geometry} material={materials['3DPrint_White_Frame']} />
        <mesh geometry={nodes.Curve005_2.geometry} material={materials['Material.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/clover.glb')
